### ISSUE TITLE
Adding support for IETF chacha20poly1305

### ISSUE THREAD

**Issue by chantra** [DNSCrypt/dnscrypt-protocol#2]
Given that there is now an IETF version, would it make sense to update the protocol and add support for it along the existing xsalsa and xchacha?

**Comment by jedisct1** [comment]
IETF ChaCha was tailored for TLS. It has a smaller nonce size and would not be a good fit.

If we want to support for an IETF construction, I think we should use HPKE instead, even if restricted to X25519 and ChaChaPoly.
