### ISSUE TITLE
spec error: tcp length prefix encoded as bigendian instead of little endian

### ISSUE THREAD

**Issue by reklatsmasters** [DNSCrypt/dnscrypt-protocol#5]
Spec says:

> Client queries over TCP only differ from queries sent over UDP by the
padding length computation and by the fact that they are prefixed with
their length, **encoded as two little-endian bytes**.

But tcp length actualy encoded as big endian!

https://github.com/jedisct1/encrypted-dns-server/blob/641ba88ab1fd635524aee47afbba5887c52e1438/src/resolver.rs#L149-L152

I spend a hours to understand why i don't get response from server over tcp.

**Comment by alex14fr** [comment]
I went through the same issue ;-)

**Comment by jedisct1** [comment]
Thanks!
